---
title: "Traditional Recipes"
author: "jewishfoodsociety.org"
format: pdf
---

# Kreplach

## Yield

90 dumplings

## Ingredients

For the filling:

* 6 tablespoons canola oil
* 1 small chicken breast (about 5 ounces; ½ cup chopped), cut into ½-inch pieces
* 3 chicken livers (about 3 ounces; ¼ cup chopped), cut into ½-inch pieces
* ½ teaspoon kosher salt, plus more to taste
* 3 medium onions, roughly chopped
* 1 egg, lightly beaten, divided
* ½ teaspoon freshly ground black pepper

For the dough:

* 3½ cups all-purpose flour, sifted
* 1 tablespoon salt
* 1 egg, lightly beaten
* 1 cup lukewarm water
* Canola oil, for drizzling

For serving:

* Chicken soup
* Fried onions

## Preparation

* Step 1: Heat 4 tablespoons of the oil in a medium pan over medium-high heat. Season the chicken and liver pieces lightly with salt. Add to the pan and sear, turning occasionally, until browned on all sides and cooked through, 5 to 7 minutes. Transfer the pieces to a plate and set aside to cool slightly.
* Step 2: Add the remaining oil to the pan along with the onions and sauté, stirring occasionally, until the onions are golden brown and beginning to caramelize, about 10 minutes. Season lightly with salt and remove from the heat. Set aside to cool slightly.
* Step 3: Transfer the chicken and liver to a food processor, along with the onions, 1½ tablespoons of the beaten egg, the ½ teaspoon of the salt, and all of the pepper. Pulse the mixture until it is finely ground and reseason to taste. Transfer to a small bowl and cover loosely with plastic wrap. Set aside to cool completely.
* Step 4: Meanwhile, make the dough: Combine the flour and salt in a medium bowl and make a well in the center. Whisk the egg with 1 cup of water and the remaining egg from the filling. Pour the egg mixture into the well in the dry ingredients and mix with a fork until a shaggy dough forms.
* Step 5: Turn the dough onto a lightly floured surface and knead until soft and smooth, 1 to 2 minutes. Return the dough to the bowl, cover with a towel or plastic wrap, and set aside to rest for 20 minutes.
* Step 6: Line a baking sheet with wax or parchment paper and drizzle evenly with oil. Divide the dough into thirds with a dough cutter or chef’s knife. Transfer one-third of the dough to a heavily floured surface, keeping the other two-thirds covered. Using a rolling pin, roll out the dough as thinly as possible into an 20-inch by 14-inch rectangle.
* Step 7: Using a pizza cutter or chef’s knife, cut the rolled dough into 2-inch squares. Place ½ teaspoon of filling in the middle of each square. Lightly brush the edges with water and fold each square in half over the filling to form a triangle, pressing the edges gently together to create a tight seal. Fold the two longer corners inward to connect and clasp along the longest edge of each dumpling, pressing to seal tortellini-style. Place on the prepared baking sheet, cover loosely with plastic wrap, and continue with the remainder of the dough and filling.
* Step 8: While forming the dumplings, bring a large pot of generously salted water to a boil. Working in two batches, gently slide the dumplings into the water. Simmer 3 to 4 minutes until the dumplings float to the surface. Remove the dumplings with a slotted spoon to a wax or parchment paper-lined tray.
* Step 9: To serve, add the cooked dumplings to hot chicken soup or fry them in a pan with onions.

Make Ahead: The filling can be made in advance and refrigerated in an airtight container for 1 to 2 days. The dumplings can be made ahead and placed on a wax or parchment paper-lined tray in the freezer until firm, then transferred to a resealable airtight bag and stored in the freezer for 1 to 2 weeks. Add the frozen dumplings directly to the boiling water and continue to cook 2 to 3 minutes after they float to the surface.

# Matzo Ball Soup

## Yield

6 - 8 servings

## Ingredients

For the soup:

* 1 onion, peeled and halved
* 1 to 2 leeks, white and pale-green parts only, chopped in half crosswise
* 4 to 5 carrots, peeled and roughly chopped
* 3 parsley roots with parsley leaves, peeled
* 7 to 8 celery stalks, peeled and roughly chopped
* 6 chicken drumsticks, bone-in, skin-on
* 6 chicken wings, bone-in, skin-on
* 1½  tablespoons kosher salt
* 1 bunch fresh dill

For the matzo balls:

* 1 cup matzo meal
* 4 eggs
* ¼ cup chicken broth
* 3 tablespoons olive oil
* ¼ teaspoon onion powder
* ¼ teaspoon garlic powder
* 1½ teaspoons kosher salt
* 1 pinch white pepper

## Preparation

* Step 1

  * Make the soup: Place the onion, leeks, carrots, parsley roots, celery, chicken drumsticks and wings, and salt in a large pot. Add 3 quarts of water (around 12-13 cups) of cold water. Place over high heat uncovered to bring the pot to boil, about 30 minutes.

* Step 2

  * Turn down the heat to a simmer, cover the pot with a lid and allow to cook for 2 hours. Use a large slotted spoon to skim off any impurities that rise to the surface. If the soup liquid reduces significantly during cooking, top it off with an additional 2 cups of boiling water.

* Step 3

  * Add the dill and simmer for an additional 15 minutes.

* Step 4

  * Remove the soup pot from the heat. Strain the soup through a large sieve or strainer. Reserve the onion, carrots, and chicken pieces.

* Step 5

  * Make the matzo balls: Whisk the matzo meal, eggs, chicken soup, olive oil, onion powder, garlic powder, kosher salt and white pepper in a mixing bowl until combined. Cover the matzo ball mixture with plastic wrap and set it to cool in the refrigerator for 20 minutes until the matzo meal absorbs the liquid and the mixture sets near firm.

* Step 6

  * In a large pot bring about 3 quartz of water to a boil with 2 tablespoons of kosher salt.

* Step 7

  * Transfer the matzo ball mixture from the refrigerator. Place a tablespoonful of the mixture between the palm of your hands and shape the matzo ball into a sphere. Drop the matzo ball into the boiling water and continue with the rest of the matzo ball mixture. Wet your hands with cold water if the mixture sticks to your hands during the process.

* Step 8

  * Once all the matzo balls are placed in the pot, bring it back up to a boil and turn down the heat to a simmer. Cover the pot and cook for another hour, until the matzo balls have risen from the bottom and have expanded to about twice their original size.

* Step 9

  * To serve, ladle the strained soup into a bowl and top with a piece of onion, celery, carrot, chicken and 1 to 2 matzo balls. Serve hot.
