# Generated by cpp11: do not edit by hand

set_poppler_data <- function(path) {
  .Call(`_cpp11poppler_set_poppler_data`, path)
}

get_poppler_config <- function() {
  .Call(`_cpp11poppler_get_poppler_config`)
}

poppler_pdf_info <- function(x, opw, upw) {
  .Call(`_cpp11poppler_poppler_pdf_info`, x, opw, upw)
}

poppler_pdf_data <- function(x, get_font_info, opw, upw) {
  .Call(`_cpp11poppler_poppler_pdf_data`, x, get_font_info, opw, upw)
}

poppler_pdf_text <- function(x, opw, upw) {
  .Call(`_cpp11poppler_poppler_pdf_text`, x, opw, upw)
}

poppler_pdf_pagesize <- function(x, opw, upw) {
  .Call(`_cpp11poppler_poppler_pdf_pagesize`, x, opw, upw)
}

poppler_pdf_fonts <- function(x, opw, upw) {
  .Call(`_cpp11poppler_poppler_pdf_fonts`, x, opw, upw)
}

poppler_pdf_files <- function(x, opw, upw) {
  .Call(`_cpp11poppler_poppler_pdf_files`, x, opw, upw)
}

poppler_pdf_toc <- function(x, opw, upw) {
  .Call(`_cpp11poppler_poppler_pdf_toc`, x, opw, upw)
}

poppler_render_page <- function(x, pagenum, dpi, opw, upw, antialiasing, text_antialiasing) {
  .Call(`_cpp11poppler_poppler_render_page`, x, pagenum, dpi, opw, upw, antialiasing, text_antialiasing)
}

poppler_convert <- function(x, format, pages, names, dpi, opw, upw, antialiasing, text_antialiasing, verbose) {
  .Call(`_cpp11poppler_poppler_convert`, x, format, pages, names, dpi, opw, upw, antialiasing, text_antialiasing, verbose)
}

set_error_callback <- function() {
  invisible(.Call(`_cpp11poppler_set_error_callback`))
}
